### ISSUE TITLE
xprintidle reports incorrect idle time 

### ISSUE THREAD

**Issue by gustden** [g0hl1n/xprintidle#2] opened 2018-05-09 20:20 UTC
I am having issues with xprintidle reporting incorrect idle time.  In looking at the code, the source of the issue is with the 'workaroundCreepyXServer' code.   I am using ubuntu 18.04 and the workaround is no longer needed, so xprintidle reports incorrect time.   I have removed the  'workaroundCreepyXServer' code  locally and it works perfectly on my release.  (  It has also been documented here by another user:  https://bugs.launchpad.net/ubuntu/+source/xprintidle/+bug/1669371 )

**Comment by g0hl1n** [comment] 2018-06-05 07:49
Hi, thank you for reporting this issue.
Which XServer version are you using?
Do you know what is the first XServer version which doesn't need the workaroundCreepyXServer  anymore?

**Comment by gustden** [comment] 2018-06-05 14:14
After more testing,  there is still an issue within the idle time reported by the Xserver when used with xscreensaver and the screen is in standby ( idle time shows less than timeout,  sometimes when screen is already off).  Although the time provided by xprintidle is not always correct,  the workaround stills seems to be beneficial in some cases.   Please close this issue, as there are clearly still problems outside the scope of xprintidle.

**Comment by fdservices** [comment] 2020-05-13 07:59
This bug still exists.

xprintidle 0.2.2
xorg-server 1.20.8
Arch linux 5.6.11

**Comment by g0hl1n** [comment] 2020-08-10 14:49
> This bug still exists.
> 
> xprintidle 0.2.2
> xorg-server 1.20.8
> Arch linux 5.6.11

Are you still able to reproduce the issue?

**Comment by fdservices** [comment] 2020-08-10 15:19
Yes it does on my Arch linux system

Linux acer 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

**Comment by g0hl1n** [comment] 2020-08-11 08:45
@fdservices can you please verify if the issue is fixed with the current refactor branch?

**Comment by fdservices** [comment] 2020-08-12 11:12
As far as I can tell the refactor version does not have this problem. I will keep checking though.

My xorg-server version is 1.20.8 - does this tie in with your comment?

**Comment by fdservices** [comment] 2020-08-12 16:15
OK, I reinstalled the master version, and I can confirm that the bug still exist there. So I think that the fix in refactor does seems to work.

**Comment by g0hl1n** [comment] 2020-08-12 17:23
Perfect. Thank you very much!

**Closed** 2020-08-12 17:23 UTC
Labels: bug
