### ISSUE TITLE
Doesnt work in ubuntu 21.04 within virtualbox

### ISSUE THREAD

**Issue by stephen-gp** [g0hl1n/xprintidle#11] opened 2021-09-20 05:14 UTC
Hello,

This package doesnt seem to work when installed on ubuntu 21.04 running within VirtualBox (6.1.26).

Typing xprintidle into the terminal returns "screen saver extension not supported".

**Comment by petterreinholdtsen** [comment] 2021-09-22 04:55
The program simply queries the X server/protocol for the idle time information.  If this query do not work within VirtualBox, the X protocol server need to be fixed, it can not be fixed in xprintidle.

**Comment by g0hl1n** [comment] 2021-09-22 06:30
Thanks for opening an issue, but I agree with @petterreinholdtsen, this is most likely caused by your X setup (especially the scrnsaverproto: https://www.x.org/releases/X11R7.7/doc/scrnsaverproto/saver.pdf).
If you have any logs/debugging output which suggest there may be a real xprintidle problem please reopen the issue :wink:

**Closed by g0hl1n** 2021-09-22 06:30 UTC

**Comment by stephen-gp** [comment] 2021-09-27 06:58
Well i dont know if this help, but installing 20.04 in VirtualBox xprintidle works as expected without any issues.
Its only on 21.04 that it appears to be broken.

So either they broke something in 21.04 or xprintidle needs to be updated to work with 21.04. 
It was the same version of virtual box for both installs.
¯\_(ツ)_/¯
